apiVersion: apps/v1
kind: Deployment
metadata:
    name: unidad03
    namespace: hotels-monolith
    labels:
        app: unidad03
spec:
    replicas: 3
    selector:
        matchLabels:
            app: unidad03
    template:
        metadata:
            labels:
                app: unidad03
        spec:
            containers:
                - name: unidad03
                image: ghcr.io --> etc